apiVersion: apps/v1
kind: Deployment
metadata:
  name: oomkill-demo
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: oomkill-demo
  template:
    metadata:
      labels:
        app: oomkill-demo
    spec:
      containers:
        - name: memory-hog
          image: python:3.11
          command:
            - python
            - -c
            - |
              import time

              x = []
              for i in range(400):  # ~40MB approx
                  x.append(" " * 10**5)

              time.sleep(300)
          resources:
            limits:
              memory: "32Mi"
            requests:
              memory: "32Mi"
